arblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
# to call static files module
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from blogArabic import views
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from blogArabic.sitemaps import PostSitemap

#### to active static when DEBUG = False ###
from django.views.static import serve
####################################"""" 

sitemaps = {
    'post': PostSitemap,
}
# this to 404.html work
handler404 = 'blogArabic.views.error_404_view'

urlpatterns = [
    
    # this to protect admin page(it is fuc admin page)
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    # this the real admin login page
    path('pythonDZ/', admin.site.urls),
    
    url(r'^', include('blogArabic.urls', namespace= 'blog')),
    
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^robots\.txt$', TemplateView.as_view(template_name="blogArabic/robots.txt", content_type='text/plain')),
   
   
   
  
   

     # this to reset password via email
    path('', include('django.contrib.auth.urls')),


    path('sitemaps.xml',sitemap, {'sitemaps': sitemaps} ),
    #### to active static when DEBUG = False ###
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    ##########################################################################
]

# to add static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blogArabic/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm

from .import views

app_name="blogArabic"
urlpatterns = [
    # home page
    url(r'^$', views.index, name='index'),
    #open login page
    url(r'^login/$', views.login, name = 'login'),
    #open register page
    url(r'^register/$', views.register, name = 'register'),

    #check login
    url(r'^auth/$', views.auth_views, name='auth_views'),

   # logout or Disconnect
   url(r'^logout/$', views.logout, name ='logout'),

   # create post
   url(r'create/$', views.create_article, name='create_article'),

   #publish
   url(r'publish/$', views.publish, name='publish'),

   #chose avatar
   url(r'avatar/$', views.avatar, name='avatar'),

   url(r'profile/$', views.getProfile, name="getProfile"),

   url(r'^like/$', views.like_post, name="like_post"),


  
   # about page
   url(r'about/$', views.about, name="about"),

   # contact page
   url(r'contact/$', views.contact, name="contact"),

   #show category
   url(r'show_category/$', views.show_category, name="show_category"),
   # to go to spicial id when click a link 
   url(r'article/(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.show_article, name='show_article'),

   # TO SHOW PROFILE
   url(r'user/(?P<id>\d+)/$', views.show_profile, name='show_profile'),
   
   
   # show solo category articles
   url(r'topic/(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.getTopic, name="getTopic"),
   #reset password page from email
   url(r'reset_password/$', views.reset_pass, name='reset_pass'),
   #send lik to reset password
   url(r'^password_email/$', views.send_pass_link, name='send_pass_link'),
   #faq page
   url(r'^faq/$', views.faq, name='faq'),
   #search page
   url(r'^search/$', views.search, name='search'),

   #contact add comment
   url(r'^contact_send/$', views.contact_comment, name='contact_comment'),
   
   url(r'delete/(?P<pid>\d+)/$', views.getDelete, name="getDelete"),
   url(r'update/(?P<pid>\d+)/$', views.getUpdate, name="getUpdate"),

   #change password from profile
   url(r'password_change/$', views.change_password, name='change_password'),

   #terms service
   url(r'terms_services/$', views.terms_service, name='terms_service'),

   #privacy page
   url(r'privacy/$', views.privacy, name='privacy'),
    #put comment to publish
   
   url(r'add_comment/(?P<id>\d+)/$', views.save_comment, name='save_comment'),
  



    # urls to change password user via Email ############################################################""
   url(r'^password_reset/$', auth_views.password_reset, {"template_name": "regi/password_reset_form.html", 
        "post_reset_redirect": "password_reset_done", "email_template_name": "regi/password_reset_email.html"}, name='password_reset'),

   url(r'^password_reset/done/$', auth_views.password_reset_done, {"template_name": "regi/password_reset_done.html"}, name='password_reset_done'),
        
   url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {"template_name": "regi/password_reset_confirm.html"}, name='password_reset_confirm'),
   url(r'^reset/done/$', auth_views.password_reset_complete, {"template_name": "regi/password_reset_complete.html"}, name='password_reset_complete'),
    ##############################################################################################
  
     #account confirmations
   path('activate/<uid>/<token>', views.activate, name="activate"),


   
    
    
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blogArabic/models.py
from django.shortcuts import reverse, Http404
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.postgres.fields import JSONField
import hashlib
from colorful.fields import RGBColorField
from django.utils import timezone 
from django.template.defaultfilters import slugify
from tinymce.models import HTMLField


# Create your models here.


def arabic_slugify(str):
    str = str.replace(" ", "-")
    str = str.replace(" ' ", "-")
    str = str.replace('"', '-')
    str = str.replace(" ّ ", "-")
    str = str.replace(".", "")
    str = str.replace("،", "-")
    str = str.replace(",", "-")
    str = str.replace("(", "-")
    str = str.replace(")", "")
    str = str.replace("؟", "")
    return str



class Category(models.Model):
    name = models.CharField(max_length=200)
    image_category = models.ImageField(null = True, blank = True, upload_to = 'Category_images')
    color = RGBColorField(colors=['#FF0000', '#00FF00', '#0000FF', '#17a589'])
    slug = models.SlugField(max_length=250, allow_unicode=True)
    
    
    

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
   
   

   

  



class author(models.Model):
    name = models.ForeignKey(User, on_delete=models.CASCADE)
   
    profile_picture = models.ImageField(blank = True, upload_to = 'Avatar', default= 'Avatar/deafult-profile-image.png')
    job = models.CharField(max_length = 500, blank = True, null = True)
    firstname = models.CharField(max_length = 500, blank = True, null = False)
   
    age = models.IntegerField(blank = True, null = True)
    gender = models.CharField(max_length = 500, blank = True, null = True)
    pays = models.CharField(max_length = 500, blank = True, null = True)
    level = models.CharField(max_length = 500, blank = True, null = True)
    facebook_account = models.CharField(max_length = 500, blank = True, null = True)
    instagram_account = models.CharField(max_length = 500, blank = True, null = True)
    youtube_channel = models.CharField(max_length = 500, blank = True, null = True)
    twitter_account = models.CharField(max_length = 500, blank = True, null = True)



    def read(self):
        # 总阅读量
        bs = articles.objects.only("read").filter(author_id=self.id)
        return sum([b.read for b in bs])

    read.short_description = "阅读量"


   

    def __str__(self):
        return self.name.username


    


class articles(models.Model):
    article_author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, max_length=200, on_delete=models.CASCADE)
    avatar = models.ForeignKey(author, on_delete = models.CASCADE)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    featured = models.BooleanField(default=False)
    

    title = models.CharField('العنوان', max_length=9500)
    slug = models.SlugField(max_length=9500, unique_for_date='publish', allow_unicode=True)
    image = models.ImageField('صورة مناسبة', upload_to = 'Images')
    taker_image = models.CharField('ملتقط الصورة', max_length=200)
    source = models.CharField('المصدر', max_length=200)
    body = HTMLField()
   

    posted_on = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True, auto_now_add=False)
    read = models.PositiveIntegerField(default=0, verbose_name='阅读数')
    publish = models.DateTimeField(default=timezone.now) 
   
    
    
    
    def __str__(self):
        return '%s %s %s' % (self.title, '/', self.category)

    def snippet(self):
        return '%s %s ' % (self.body[:120], '......' )

    def snippet1(self):
        return '%s %s ' % (self.body[:200], '......' )

    def snippet2(self):
        return '%s %s ' % (self.body[:100], '......' )

    def small_title(self):
        return '%s %s ' % (self.title[:40], '......' )

    
    def total_likes(self):
        return self.likes.count()

    def save(self, *args, **kwargs):
    
        if not self.slug:
            self.slug = slugify(self.title)
            if not self.slug:
                self.slug = arabic_slugify(self.title)

        super(articles, self).save(*args, **kwargs)

    



    


    def is_featured(self):
        return self.featured

    def is_read(self):
        return self.read

    def get_absolute_url(self):
        return reverse('blogArabic:show_article', kwargs={'id':self.id, 'slug': self.slug})

   

class Visit(models.Model):
    post = models.ForeignKey(articles, on_delete=models.CASCADE)
    ip = models.GenericIPAddressField()
    visit_count = models.IntegerField(default=0)

   



class contactModel(models.Model):
    
    
    username1 = models.CharField(max_length = 500, blank = True, null = True)
    email = models.CharField(max_length = 500, blank = True, null = True)
    text_body = models.TextField(max_length = 500, blank = True, null = True)

    def __str__(self):
        return self.username1




class comment_put(models.Model):

    user_comment = models.ForeignKey(User, default = None, on_delete = models.CASCADE)
    user_put = models.ForeignKey(articles, on_delete = models.CASCADE)
    avatar_commenter = models.ForeignKey(author, on_delete = models.CASCADE)
    comment = models.TextField(max_length = 500)
    date = models.DateTimeField(auto_now=False, auto_now_add=True)
   
    def __str__(self):
        return self.comment

blogArabic/forms.py
from django import forms
from django.db import models
from tinymce.widgets import TinyMCE

from blogArabic.models import articles, author, comment_put
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False

# add multy fields to register page
class MyRegistrationForm(UserCreationForm):
   
   email = forms.EmailField(required = True)
  
  


   class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

   def save(self, commit = True):
        user = super(MyRegistrationForm, self).save(commit = False)
       
        user.email = self.cleaned_data['email']
       

        if commit:
                user.save()
        return user 

   def clean_email(self):
      email = self.cleaned_data['email']
      qs = User.objects.filter(email = email)
      if qs.exists():
          raise ValidationError ('Email is already registed')
      return email


   def check_email(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email__iexact=email, is_active=True).exists():
            raise ValidationError("There is no user registered with the specified email address!")

        return email 



class createForm(forms.ModelForm):
    body = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )
    class Meta:
        model = articles
        fields = [
            'category',
            'title',
            'image',
            'taker_image',
            'body',
            'source',
          
        ]
class createAuthor(forms.ModelForm):
    class Meta:
        model = author
        fields = [
            'profile_picture',
            'job',
            'pays',
            'firstname',
            'age',
            'gender',
            'level',
            'facebook_account',
            'instagram_account', 
            'youtube_channel',  
            'twitter_account', 
        ]

class CommentForm(forms.ModelForm):

        class Meta:
                model = comment_put
                fields =[
                 'comment',
                 
                ]

blogArabic/templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="utf-8">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

 <title>{% block title %}{% endblock %}</title>

 

    
    <link href="https://fonts.googleapis.com/css?family=Cairo|Lalezar" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Lalezar" rel="stylesheet"> 
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %}" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main12.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main6.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-rtl.css' %}">
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
     
   <script src="http://apps.bdimg.com/libs/html5shiv/3.7/html5shiv.min.js"></script>
   <script src="http://apps.bdimg.com/libs/respond.js/1.4.2/respond.min.js"></script>

   <!-- FOR CODESNIPPET theme monokai_sublime-->
   <link rel="stylesheet" type="text/css" href="{% static 'css/monokai_sublime.css' %}">
   <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
   <script src="/static/base/js/main.js"></script>
   <script>hljs.initHighlightingOnLoad();</script>
   <!-- end theme -->


 

    
  

</head>

 

<body class="rtl">

 

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="margin-top: 20em; ">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="background-color:#32234b; color:#fff; font-family: 'Cairo', sans-serif;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">تسجيل الخروج</h5>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        يسعدنا توجدك مرة أخرى
        <a class="text-info" href="/logout/" style="text-decoration: none; margin-right: 2em;">تسجيل الخروج</a>
      </div>
     
    </div>
  </div>
</div>

  
 <!-- create small navbar -->



 
 <div class="navbar navbar-inverse navbar-expand-lg fixed-top navbar-dark bg-primary shadow p-3 mb-5 bg-white rounded" style="background-color: #32234b !important;">
 	
        <div class="container">

            <a href="/" class="navbar-brand " style="font-size: 2.4em;">المدونات العربية</a>

            

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav" >
                  
                    <li class="nav-item">
                        <a class="nav-link my-2" href="/contact/">اﺗﺼﻞ ﺑﻨﺎ</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link my-2" href="/faq/">التعليمات</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link my-2" href="/about/">ﻣﻦ ﻧﺤﻦ</a>
                    </li>
                     <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle my-2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          المقالات
        </a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           <div class="dropdown-divider"></div>
          
          <a class="dropdown-item" href="/topic/12/" >المجتمع</a>
          <a class="dropdown-item" href="/topic/4/">الإقتصاد</a>
           <a class="dropdown-item" href="/topic/5/">الصحة</a>
          <a class="dropdown-item"  href="/topic/6/">البيئة</a>
          <a class="dropdown-item" href="/topic/8/">الرياضة</a>
          <a class="dropdown-item" href="/topic/7/">الإبتكار و التكنولوجيا</a>
          <a class="dropdown-item" href="/show_category/">المزيد...</a>
          
          
              
        </div>
      </li>

                      <li class="nav-item">
                        <a class="nav-link my-2" href="/search/"><i class="fas fa-search text-warning" style="font-size: 1.5em;"></i></a>
                    </li>
                   
                 
                </ul>

                <ul class="nav navbar-nav ml-auto">

                    <!-- when loggedin -->
                    {% if request.user.is_authenticated %}
                     <li class="nav-item dropdown my-2">
                        <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="" id="themes" > {{full_name}}  <span class="caret"></span>
                         <img class="rounded-circle"  src="{{ request.user.author_set.first.profile_picture.url }}" style="max-width: 2.5em; margin-right: 10px;height: 2.5em;"> </a>
                        <div class="dropdown-menu" aria-labelledby="themes">
                           
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/profile/">حسابي</a>
                            <a class="dropdown-item" href="/create/" >إضافة مقال</a>
                            <a class="dropdown-item" href="#" style="margin-top: 1em;" data-toggle="modal" data-target="#exampleModal">تسجيل خروج</a>
                             
                           
                            
                        </div>
                    </li>
                    {% else %}
                    <!-- end loggedin -->

                    <!-- visited user -->
                    <li class="nav-item">
                        <a class="nav-link" href="/register/" >فتح حساب</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/login/" >تسجيل دخول</a>
                    </li>
                    

                    <!-- end visited user -->

                    {% endif %}

                    
                </ul>
             
            </div>
        </div>
    </div>
    <div class="container">
        <div class="page-header" id="banner">
            <div class="row">
                
               
            </div>
        </div>


    </div>
    
 <!-- end small navbar-->


 
 
       




 {% block content %}



{% endblock %}
 <!-- js -->

  <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'vendor/jquery-2.1.4.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/scripte2.js' %}"></script>
 {% block script %}{% endblock %}
  
   
  <!-- end js -->


   








  <!-- footer -->
    

       <footer >
   
    
    <div class="container" style="border-top:1px solid grey;">
        <div class="row text-center">   

            <div class="col-lg-6 col-lg-offset-3">

                  <div class="foot-link">
                   

                      <ul>


                        <li class="fb"><a href="https://web.facebook.com/django.756859"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li class="tw"><a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li class="gp"><a href=""><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li  class="lin"><a href=""><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                       
                      </ul>
                      </div>

                <ul class="menu">

                    <li>
                        <a href="/show_category/">المقالات</a>
                    </li>
                           
                    <li>
                        <a href="/search/">البحث</a>
                    </li>
                           
                    <li>
                        <a href="/about/">ﻣﻦ ﻧﺤﻦ</a>
                    </li>
                           
                    <li>
                        <a href="/contact/">اﺗﺼﻞ ﺑﻨﺎ</a>
                    </li>
                           
                   
                    
                   
                </ul>

            </div>
        </div>
    </div>
</footer>
<!-- end footer -->

<!-- copyright -->


<div class="container">
  <div class="row shadow-sm p-3 mb-5 bg-white rounded">
  <hr>
    
      <div class="col-md-3">
        <a href="/terms_services">شروط الخصوصية</a> | <a href="/privacy">اﻟﺨﺼﻮﺻﻴﺔ</a>    
      </div>

      <div class="col-md-7">

        <p class="muted pull-right" >© 2018 Company Name. جميع الحقوق محفوظة</p>


    
      </div>
      <div class="col-md-2 ">
       <i class="fas fa-chevron-circle-up add" id="#top" style="cursor: pointer;"></i>
      </div>
     


      </div>
    
  </div>
</div>

<!-- end copyright -->

 
 





</body>
</html>