arblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
# to call static files module
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from blogArabic import views
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from blogArabic.sitemaps import PostSitemap

#### to active static when DEBUG = False ###
from django.views.static import serve
####################################"""" 

sitemaps = {
    'post': PostSitemap,
}
# this to 404.html work
handler404 = 'blogArabic.views.error_404_view'

urlpatterns = [
    
    # this to protect admin page(it is fuc admin page)
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    # this the real admin login page
    path('pythonDZ/', admin.site.urls),
    
    url(r'^', include('blogArabic.urls', namespace= 'blog')),
    
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^robots\.txt$', TemplateView.as_view(template_name="blogArabic/robots.txt", content_type='text/plain')),
   
   
   
  
   

     # this to reset password via email
    path('', include('django.contrib.auth.urls')),


    path('sitemaps.xml',sitemap, {'sitemaps': sitemaps} ),
    #### to active static when DEBUG = False ###
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    ##########################################################################
]

# to add static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blogArabic/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm

from .import views

app_name="blogArabic"
urlpatterns = [
    # home page
    url(r'^$', views.index, name='index'),
    #open login page
    url(r'^login/$', views.login, name = 'login'),
    #open register page
    url(r'^register/$', views.register, name = 'register'),

    #check login
    url(r'^auth/$', views.auth_views, name='auth_views'),

   # logout or Disconnect
   url(r'^logout/$', views.logout, name ='logout'),

   # create post
   url(r'create/$', views.create_article, name='create_article'),

   #publish
   url(r'publish/$', views.publish, name='publish'),

   #chose avatar
   url(r'avatar/$', views.avatar, name='avatar'),

   url(r'profile/$', views.getProfile, name="getProfile"),

   url(r'^like/$', views.like_post, name="like_post"),


  
   # about page
   url(r'about/$', views.about, name="about"),

   # contact page
   url(r'contact/$', views.contact, name="contact"),

   #show category
   url(r'show_category/$', views.show_category, name="show_category"),
   # to go to spicial id when click a link 
   url(r'article/(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.show_article, name='show_article'),

   # TO SHOW PROFILE
   url(r'user/(?P<id>\d+)/$', views.show_profile, name='show_profile'),
   
   
   # show solo category articles
   url(r'topic/(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.getTopic, name="getTopic"),
   #reset password page from email
   url(r'reset_password/$', views.reset_pass, name='reset_pass'),
   #send lik to reset password
   url(r'^password_email/$', views.send_pass_link, name='send_pass_link'),
   #faq page
   url(r'^faq/$', views.faq, name='faq'),
   #search page
   url(r'^search/$', views.search, name='search'),

   #contact add comment
   url(r'^contact_send/$', views.contact_comment, name='contact_comment'),
   
   url(r'delete/(?P<pid>\d+)/$', views.getDelete, name="getDelete"),
   url(r'update/(?P<pid>\d+)/$', views.getUpdate, name="getUpdate"),

   #change password from profile
   url(r'password_change/$', views.change_password, name='change_password'),

   #terms service
   url(r'terms_services/$', views.terms_service, name='terms_service'),

   #privacy page
   url(r'privacy/$', views.privacy, name='privacy'),
    #put comment to publish
   
   url(r'add_comment/(?P<id>\d+)/$', views.save_comment, name='save_comment'),
  



    # urls to change password user via Email ############################################################""
   url(r'^password_reset/$', auth_views.password_reset, {"template_name": "regi/password_reset_form.html", 
        "post_reset_redirect": "password_reset_done", "email_template_name": "regi/password_reset_email.html"}, name='password_reset'),

   url(r'^password_reset/done/$', auth_views.password_reset_done, {"template_name": "regi/password_reset_done.html"}, name='password_reset_done'),
        
   url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {"template_name": "regi/password_reset_confirm.html"}, name='password_reset_confirm'),
   url(r'^reset/done/$', auth_views.password_reset_complete, {"template_name": "regi/password_reset_complete.html"}, name='password_reset_complete'),
    ##############################################################################################
  
     #account confirmations
   path('activate/<uid>/<token>', views.activate, name="activate"),


   
    
    
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blogArabic/forms.py
from django import forms
from django.db import models
from tinymce.widgets import TinyMCE

from blogArabic.models import articles, author, comment_put
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False

# add multy fields to register page
class MyRegistrationForm(UserCreationForm):
   
   email = forms.EmailField(required = True)
  
  


   class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

   def save(self, commit = True):
        user = super(MyRegistrationForm, self).save(commit = False)
       
        user.email = self.cleaned_data['email']
       

        if commit:
                user.save()
        return user 

   def clean_email(self):
      email = self.cleaned_data['email']
      qs = User.objects.filter(email = email)
      if qs.exists():
          raise ValidationError ('Email is already registed')
      return email


   def check_email(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email__iexact=email, is_active=True).exists():
            raise ValidationError("There is no user registered with the specified email address!")

        return email 



class createForm(forms.ModelForm):
    body = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )
    class Meta:
        model = articles
        fields = [
            'category',
            'title',
            'image',
            'taker_image',
            'body',
            'source',
          
        ]
class createAuthor(forms.ModelForm):
    class Meta:
        model = author
        fields = [
            'profile_picture',
            'job',
            'pays',
            'firstname',
            'age',
            'gender',
            'level',
            'facebook_account',
            'instagram_account', 
            'youtube_channel',  
            'twitter_account', 
        ]

class CommentForm(forms.ModelForm):

        class Meta:
                model = comment_put
                fields =[
                 'comment',
                 
                ]

blogArabic/views.py
from django.shortcuts import render, Http404, get_object_or_404, redirect, HttpResponse, reverse
from django.shortcuts import render_to_response  
from urllib.parse import quote 
from django.template.context_processors import csrf
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth.admin import UserAdmin
from django.contrib.auth.forms import UserCreationForm
from blogArabic.forms import MyRegistrationForm
from django.contrib.auth.forms import PasswordChangeForm
from blogArabic.forms import createForm, createAuthor, CommentForm
from django.forms import ModelForm
from django.contrib.auth.models import User
from blogArabic.models import author, articles, Category, contactModel, comment_put
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import update_session_auth_hash
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.conf import settings
from django.core.mail import send_mail
from .token import activation_token
from django.contrib.auth.forms import PasswordChangeForm
from django.template import loader
from django.db.models import Q
from django.template.defaultfilters import slugify
#htiscounter


def error_404_view(request, exception):
    return render(request,'blogArabic/404_error.html')



def search(request): 
           all_articles = articles.objects.all().order_by('-id')
             # to search in loggedin page
           search = request.GET.get('q')
           if search:
              messages.success(request, 'تم البحث', extra_tags='search')
              all_articles = all_articles.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)  | 
                Q(article_author__username__icontains=search) 

              )
              #add paginator
           paginator = Paginator(all_articles, 15)  # Show 25 contacts per page

           page = request.GET.get('page')
           total_articles = paginator.get_page(page)
  

           return render(request, 'home/search.html', {'all_articles': total_articles, 
            'full_name': request.user.username})

# Create your views here.
#faq page
def faq(request):
       
        return render(request, 'home/faq.html', {'full_name': request.user.username})

#reset password page
def reset_pass(request):

        return render(request, 'home/reste_pass.html')

#category page
def show_category(request):
        
        query = Category.objects.all()
       
        
        return render(request, 'home/category.html', {"topic": query, 'full_name': request.user.username})

# open home page
def index(request):
         
           all_articles = articles.objects.all().order_by('-id')
           
           solo = articles.objects.order_by('-id')[:1]
           solo1 = articles.objects.order_by('-id')[:3]
           featured = articles.objects.filter(featured=True).order_by('-featured')[:4]



            # end search 
           
           #show five articles plus read
           article_read = articles.objects.filter().order_by('-read')[:4]
           #show spicial articles
           
           # show first article
           first = articles.objects.order_by('-id')[:10]
          
             # show fourth articles
           fourth = articles.objects.order_by('-id')[:4]
         

           return render(request, 'home/index.html', {'full_name': request.user.username, 'first_article':first, 
            'fourth_article':fourth, 'all_articles': all_articles, 'five_articles': article_read, 'solo': solo, 
            'solo1': solo1, 'featured': featured}) 



# about page
def about(request):
        
       
       query = contactModel.objects.order_by('-id')[:4]
       return render(request, 'home/about.html', {'full_name': request.user.username, 'query': query})
#contact page
def contact(request):
        
        
       
        return render(request, 'home/contact.html', {'full_name': request.user.username})
#open login page
def login(request):

    c = {}
    c.update(csrf (request))
    return render_to_response('home/login.html', c)

# function to see if the username and password user there is in database        
def auth_views(request):
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        

        user  = auth.authenticate(username = username, password = password)

        if user is not None:
                auth.login(request, user)
                # when user have pic profile rederect loggedin page 
                user = get_object_or_404(User, id=request.user.id)
                author_profile = author.objects.filter(name=user.id)
                if author_profile:
                       authorUser = get_object_or_404(author, name=request.user.id)

                       messages.success(request, 'مرحبا بك ', extra_tags='welcome')
                       
                       return HttpResponseRedirect('/')

                # else rederect to chose pic profile
                else:
                           
                           return HttpResponseRedirect('/avatar')
               
                
              
                
        else: 
                
                messages.success(request, 'إسم المستخدم أو كلمة السر غير صحيحة', extra_tags='passwordWrong')
                return HttpResponseRedirect('/')
                




#chose avatar 
def avatar(request):
        return render(request, 'home/avatar.html')

#logout or Desconnect
def logout(request):

    auth.logout(request)
   
    
    return HttpResponseRedirect('/')



# create register function
def register(request):
        
    form = MyRegistrationForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.is_active = False
        instance.save()
        site=get_current_site(request)
        mail_subject="Confirmation message for me"
        message=render_to_string('home/confirm_email.html',{
            'user':instance,
            'domain':site.domain,
            'uid':instance.id,
            'token':activation_token.make_token(instance)
        })
        to_email=form.cleaned_data.get('email')
        to_list=[to_email]
        from_email=settings.EMAIL_HOST_USER
        send_mail(mail_subject, message, from_email, to_list, fail_silently=False)
        return HttpResponse("<h1>Thanks for your registration. A confirmation link was sent to your email</h1>")
      
    return render(request, 'home/register.html', {"form": form})


# redrect from register form to avatar html file

def send_pass_link(request):
      email = request.POST.get('email', '')
      user = auth.authenticate(email = email)
      if user is not None:
         site = get_current_site(request)
         mail_subject = "Reset Password"
         message = render_to_string('home/reset_password.html', {
             
            'user':instance,
            'domain':site.domain,
            'uid':user.id,
            'token':activation_token.make_token(user)
         })
         to_email=form.cleaned_data.get('email')
         to_list=[to_email]
         from_email=settings.EMAIL_HOST_USER
         send_mail(mail_subject, message, from_email, to_list, fail_silently=True)
         return HttpResponse("<h1>Thanks we well send you link to reset your password !</h1>")
      return render(request, 'home/reste_pass.html')


# to pass to page to create one article     
def create_article(request):
    
       
        
    if request.user.is_authenticated:

        user = get_object_or_404(User, id=request.user.id)
        
        author_profile = author.objects.filter(name=user.id)

        # check if user has pic profile
        if author_profile:
          #if user has pic profile 
          form = createForm(request.POST or None, request.FILES or None)
          if form.is_valid():
           instance = form.save(commit = False)
           instance.save()
          return render(request, 'home/post.html', {"form": form, 'full_name': request.user.username})
        # if user has not pic profile
        else:
            form = createAuthor(request.POST or None, request.FILES or None)
            if form.is_valid():
                ins = form.save(commit = False)
                ins.name = user
                ins.save()
                
                return HttpResponseRedirect('/')
            return render(request, 'home/avatar.html', {"form": form})
    else:
      HttpResponseRedirect('/login')

     
        
    

def publish(request): 
       
        if request.user.is_authenticated:
          user = get_object_or_404(User, id=request.user.id)
          
          author_profile = author.objects.filter(name=user.id)
        
          authorUser = get_object_or_404(author, name=request.user.id)
          
    
          form = createForm (request.POST or None, request.FILES or None)
          

          if form.is_valid():
            
            instance = form.save(commit=False)
           
        # pass instance author
            instance.avatar = authorUser
        # pass instance user login
            instance.article_author = request.user
          

            instance.save()

        #pass from data base to template
            messages.success(request, 'تم نشر المقال', extra_tags='Done')
            redirect_to = reverse('blogArabic:show_article', kwargs={'id': instance.id, 'slug': instance.slug})
            return redirect(redirect_to)
          return render(request, 'home/index.html', {'form': form, 'user': authorUser, 'full_name': request.user.username})
         
        
        else:
          return HttpResponseRedirect('/login')

# show the true link publish(details)
def show_article(request, id, slug):

    
   
    
            # show second article

blogArabic/templates/home/article.html
{% extends 'base.html' %}

{% load static %}
{% block title %}{{art.title}}{% endblock %}
{% block content %}





{% if messages %}
    <div class="alert alert-success text-center " style="margin-top: 8em;">
        {% for message in messages %}

      
        <!-- when password not change -->
        {%if "commentuser" in message.tags %}
          <p> {{message}} {{full_name}} </p>   
        {%endif%} 
        <!-- end say hello --> 
            <!-- msg article published -->
        {%if "Done" in message.tags %}
          <p> {{message}}  </p>   
        {%endif%} 
        <!-- end msg article published--> 

        {% endfor %}
    </div>
    {% endif %} 

 <nav aria-label="breadcrumb " style="margin-top: 8em">
  <div class="container">
  <ol class="breadcrumb shadow p-3 mb-5 bg-white rounded">
    
    <li class="breadcrumb-item"><a href="/">الصفحة الرئسية</a></li>
    <li class="breadcrumb-item active" aria-current="page"> {{art.title}}</li>

  </ol>
  </div>

</nav>
 

  <!-- container -->
  <div class="container">
    <!-- create first row -->
  <div class="row" style="margin-top: 5em;">
    <!-- column -->
    <div class="col-lg-6 col-md-6">
        <figure class="figure ">
         <img src="{{art.image.url}}" class="figure-img img-fluid rounded" alt="A generic square placeholder image with rounded corners in a figure.">
         <figcaption class="figure-caption">{{ art.taker_image}}</figcaption>
  
        </figure>
        
    </div>
    <!-- end column -->

    <!-- column -->
    <div class="col-lg-6 shadow-lg p-3 mb-5 bg-white rounded col-md-6">
        <p class="font-weight-bold badge  py-1" style="color: #fff;background-color: {{art.category.color}}"> {{art.category}} </p>
        <p class="h1 font-weight-bold">{{art.title}}</p>

         <img src="{{ art.avatar.profile_picture.url }}" class="rounded-circle imgg" style="width: 30%; margin-top: 1.5em;">
            <a href="/user/{{art.avatar.id}}"> <figcaption class="figure-caption py-1 font-weight-bold">{{ art.article_author}}</figcaption></a>
            <p class="h6 pr" style="margin-right: 5em;">{{ art.posted_on}}</p>
            <p class="h6 pr" style="margin-right: 5em;"><i class="far fa-eye"></i> {{ art.read}}</p>


            <!-- social media -->
                                        <div class="row">
                                            <div class="col-md-8">
                                              <div class="container">
  <div class="row">
    <div class="social">
            <ul>
                <li><a href="{{art.avatar.facebook_account}}"><i class="fa fa-lg fa-facebook"></i></a></li>
                <li><a href="{{art.avatar.twitter_account}}"><i class="fa fa-lg fa-twitter"></i></a></li>
              
                <li><a href="{{art.avatar.instagram_account}}"><i class="fa fa-lg fa-instagram"></i></a></li>
               
                <li><a href="{{art.avatar.youtube_channel}}"><i class="fa fa-lg fa-youtube-play"></i></a></li>
            </ul>
        </div>
  </div>
</div>
                                              
                                            </div>
                                           
                                        </div>
                                        <!-- end social media -->
        
    </div>
    <!-- end column -->
     <div class="container">

   
        <div class="text-center center-block">
            <p class="txt-railway">مشاركة المقال</p>
            <br />
                <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_url}}"><i id="social-fb" class="fa fa-facebook-square fa-3x social" target = "_blank"></i></a>

              <a href="https://twitter.com/home?status={{request.build_absolute_url}}%20{{share_title}}"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
              <a href="https://plus.google.com/share?url=dzblog.pythonanywhere.com/article/{{art.id}}"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
              <a href="mailto:bootsnipp@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
</div>
   
</div>
      
  </div>

  <!-- end first row -->
</div>
<!-- end container -->


<div class="container">
<!-- row -->
<div class="col-lg-10">
    
    <p class="h6 pr3 " style="border-bottom: 2px #eee solid ; padding-bottom: 3em;">
        {{art.body|safe}}
       
    </p>
    
    <p class="lead" style="margin-top: 4em;">  المصدر <span style="color: #32234b">{{art.source}}</span></p>


   
     
</div>

   
<!--end row -->
</div>

<!-- like dislike-->
<!-- container-->
<div class="container">
  <!-- row-->
  <div class="row" style="margin-top: 4em;">
  
   <div class="col-lg">
  <button type="button" class="btn btn-light">
  الإعجابات <span class="badge badge-light">{{ total_likes }}</span>
</button>

 
</div>
     <!-- column -->
   <div class="col-lg-2 text-right"> 
{% if request.user.is_authenticated %}
<form action="{% url 'blogArabic:like_post' %}" method="post">
  {% csrf_token %}
  {% if is_liked %}
    <button type="submit" id="like" name="post_id" value="{{ post.id  }} " class="btn btn-danger"><i class="far fa-thumbs-down"></i></button>
  {% else %}
    <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-primary "><i class="far fa-thumbs-up " ></i></button>
  {% endif %}
</form>

{% endif %}
</div>

    <!--end column -->

  <div class="col-lg"></div>
    
  </div>
  <!-- end row-->
  
</div>
<!-- end conatiner-->
<!-- end like dislike button -->



<!-- comment text -->


<div class="comments" style="margin-top: 5em;">
  <p class="text-center border-bottom my-5">التعليقات</p>
   
      {% for cf in add %} 
    <div class="comment-wrap">
        <div class="photo">
            <div class="avatar" style="background-image: url('{{cf.avatar_commenter.profile_picture.url}}')"></div>
            <p class="text-right">{{cf.user_comment}}</p>
        </div>
        <div class="comment-block">
            <p class="comment-text">{{cf.comment }}</p>
            <div class="bottom-comment">
                <div class="comment-date">{{cf.date}}</div>
                <ul class="comment-actions">
                   
                    <!-- <li class="reply">Reply</li> -->
                </ul>
            </div>
        </div>
    </div>
    {% endfor %}

   
</div>

</div>

<!-- end comment text -->
{% if request.user.is_authenticated %}
<!--comment-->
  <div class="container">
  <div class="row" style="margin-top: 5em;">
    <h3 class="my-4">إضافة تعليق مناسب</h3>
  </div>
    
    <div class="row">
    
    <div class="col-lg-6 col-md-10 shadow-lg p-3 mb-5 bg-white rounded">
                <div class="widget-area no-padding blank">
                <div class="status-upload">
                  <form class="add_cm" action="/add_comment/{{art.id}}/" method="post">{% csrf_token %}
                    <textarea class="" placeholder="تعليق مناسب"  name="comment"></textarea>
                  
                    <button type="submit" class="btn btn-success " style="background-color: #32234b">تعليق</button>
                  </form>
                </div><!-- Status Upload  -->
              </div><!-- Widget Area -->
            </div>
        
    </div>
     
     <br/>
</div>
</div>
<!--end row -->

<!-- end comment-->
{% endif %}



  <!-- container -->
  <div class="container">
    <!-- create second row -->
  <div class="row shadow-lg p-3 mb-5 bg-white rounded" style="margin-top: 10em;" >

    <!-- column -->
    {% for fr in first %}
    <div class="col-lg-6 col-md-6">
        <p class="h6 pr1 text-primary">قراءة التالي</p>
        <p class="font-weight-bold badge  py-1" style="color: #fff;background-color: {{fr.category.color}}"> {{fr.category}} </p>
       <a class="" href="/article/{{fr.id}}/{{fr.slug}}" style="color: #212529; text-decoration: none !important;"> <p class="h1 font-weight-bold">{{fr.title}}</p></a>

         <img src="{{ fr.avatar.profile_picture.url }}" class="rounded-circle imgg" style="width: 30%; margin-top: 1.5em;">
            <p class="h6 pr" style="margin-right: 4em;">{{ fr.article_author }}</p>
            <p class="h6 pr" style="margin-right: 5em;">{{ fr.posted_on}}</p>
        
    </div>
    <!-- end column -->

    <!-- column -->
    <div class="col-lg-6 col-md-6">
        <figure class="figure">
          <a class="" href="/article/{{fr.id}}/{{fr.slug}}"><img src="{{fr.image.url }}" class="figure-img img-fluid rounded" alt="A generic square placeholder image with rounded corners in a figure."></a>
         <figcaption class="figure-caption">{{fr.taker_image}}</figcaption>
  
        </figure>
        
    </div>
    <!-- end column -->
    {% endfor %}

    
      
  </div>

  <!-- end second row -->
</div>
<!-- end container -->

<!-- container -->
<div class="container">
    <!-- third row -->
  
    
    
    <div class="row  " >
     
        <!-- column -->
         {% for td in three %}
        <div class="col-lg-3 shadow-none p-3 mb-5 bg-light rounded">

            
            <figure class="figure">
               <p class="font-weight-bold badge  py-1" style="color: #fff;background-color: {{td.category.color}}"> {{td.category}} </p>
              <a class="" href="/article/{{td.id}}/{{td.slug}}" style="color: #32234b;"> <img src="{{td.image.url}}" class="figure-img img-fluid rounded" alt="A generic square placeholder image with rounded corners in a figure." style="height: 9em;"></a>
            
           </figure>
           <a class="" href="/article/{{td.id}}" style="color: #32234b;"> <p class="h6 pr1 font-weight-bold">{{td.title}}</p></a>
           
    
            
      
           

           <p class="h6 pr2 " style="margin-top: 2em;">{{ td.article_author }}</p>
           <p class="h6 pr2 ">{{ td.posted_on }}</p>
            <p> 
                      <span class="badge badge-light">{{  td.total_likes}}</span> <i class="far fa-thumbs-up" style="color:#32234b;"></i>   
           </p>
          
        </div>
        {% endfor %}
        
        <!-- end column -->

    </div>
    <!-- end third row -->
    


    
</div>
<!-- end container -->








{% endblock %}

blogArabic/templates/home/articles_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row" style="margin-top: 10em;">
  <div class="col-md-12">
    <h1>{{object.title}}</h1>
  </div>

  <div class="col-md-8">
    <p class="lead">{{ object.content }}</p>
  </div>

  <div class="col-md-4 bg-info">
    <h2>Hitcount Info</h2>
    <dl class="dl-horizontal">
      <dt>Total Hits:</dt>
      <dd>{{ hitcount.total_hits }}</dd>
      <dt>The unique PK is:</dt>
      <dd>{{ hitcount.pk }}</dd>
      <dt>Hit counted?</dt>
      <dd id="hit-counted">
        <i id="hit-counted-value">{{ hitcount.hit_counted }}</i>
      </dd>
      <dt>Hit response:</dt>
      <dd id="hit-response">{{ hitcount.hit_message }}</dd>
      </dd>
    </dl>
  </div>
</div>
{%endblock%}

blogArabic/templates/home/confirm_email.html
{% block title %}تأكيد عبر البريد{% endblock %}
{% autoescape off %}
Hi {{ user.username }},
Thanks for your registration in blog
Please click on the link below to confirm your registration,
http://127.0.0.1:8000{% url 'blog:activate' uid=uid token=token %}
{% endautoescape %}

blogArabic/templates/home/reset_password.html
{% block title %}تأكيد{% endblock %}
{% autoescape off %}
Hi {{ user.email }},
do not worry this is a link belew click it 
Please click on the link below to go to reset your password,
http://{{ domain }}{% url 'blog:activate' uid=uid token=token %}
{% endautoescape %}

blogArabic/templates/home/reste_pass.html
{% extends 'base.html' %}
{% load static %}
{% block title %}تغيير كلمة السر{% endblock %}
{% block content %}

 <!-- container -->
 <div class="container"> 
    <!-- row -->
    <div class="row shadow-lg p-3 mb-5 bg-white rounded" style="margin-top: 15em;">
        <!-- column -->
        <div class="col-lg">
            
        </div>
        <!--end column -->

        <!-- column -->
        <div class="col-lg-5">
            <form class="config" action="/password_reset/" method="post">{% csrf_token%}
            <p class="h2 my-5  ">طلب إعادة تعيين كلمة السر</p>
              <div class="form-group">
          <label for="inputUsernameEmail">أدخل بريدك الالكتروني</label>
          <input type="email" class="form-control" id="inputUsernameEmail" placeholder="بريد الكتروني" name="email">
        </div>

        <button type="submit" class="btn btn btn-primary my-2" style="background-color: #32234b !important; border:none;">
          ارسال
        </button>
        </form>
            
        </div>
        <!--end column -->

        <!-- column -->
        <div class="col-lg">
            
        </div>
        <!--end column -->
        
    </div>
    <!-- end row -->
     
 </div>
 <!-- end container -->


{% endblock %}